name: Update npm lockfile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lockfile:
    name: Generate and commit package-lock.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: infra-ci-package-manager

      - name: Setup Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: "22.x"

      - name: Update package lock
        run: npm install --package-lock-only

      - name: Commit package-lock.json if changed
        run: |
          if git diff --quiet -- package-lock.json; then
            echo "package-lock.json is already up to date."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "chore: refresh npm lockfile"
          git push origin HEAD:infra-ci-package-manager
